- name: install nginx
  hosts: app
  become: yes
  tasks:
   - name: install naginx
     ansible.builtin.package:
      name: nginx
      state: present



   - name: start service
      ansible.builtin.service:
      name: nginx
      state: started   
      enabled: yes


