- name: print variables
  hosts: app
  tasks:
  vars:
   COURSE: "DeOPs with AWS"
   DURATION: "120Hrs"
   TRAINER: "Siva kumar"
  - name: var
    ansible.builtin.debug:
     msg: "Im learning {{COURSE}}, Duration is: {{DURATION}}; Trainer is : {{TRAINER}}"