
- name: variables from files
  hosts: app
  vars_files:
  - var.yaml
  tasks:
  - name: print the couser details
    ansible.builtin.debug:
      msg: "im learning {{COURSE}} and duration is: {{DURATION}} ad the trainer is: {{TRAINER}}" 