- name: print the files
  hosts: web
  tasks:
  - name: print the list of files
    ansible.builtin.shell: ls -ltr > text.txt

  - name: check the connection
    ansible.builtin.shell: ps -ef | grep ssh
    register: output
  - name: check the connection
    ansible.builtin.debug:
     msg: "print the pid {{output}}"
    

    
   
