- name: print the values
  hosts: web
  tasks:
  - name: convert to upper case
    vars: 
     greeting: "Hello Sai"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}" 
  - name: convert to lower case
    vars: 
     greeting: "Hello Sai"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"   
  - name: get the uniq values
    vars: 
     numbers: [1,2,4,6,33,44,55,4,21,2,1 ] 
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"     