- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the status
    ansible.builtin.debug:
     msg: "{{ansible_facts}}"
  - name: install nginx if redhat 
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "RedHat" 
  - name: install nginx if debain 
    ansible.builtin.apt:
     name: nginx
     state: present  
    when: ansible_os_family == "Debain"     