- name: install services
  hosts: web
  become: yes
  tasks:
  - name: install the given services
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop:
     - { name: 'mysql' , state: 'absent' }
     - { name: 'git' , state: 'absent' }
     - { name: 'nginx' , state: 'present' } 
     - { name: 'httpd' , state: 'absent' }