- name: intsll nginc and run
  hosts: web
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
     ansible.builtin.debug:
      msg: "nginx installed"
  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started  
     ansible.builtin.debug:
      msg: "nginx started"
     enabled: yes
     msg: "nginx enabled"
